// APP TYPES

export const APP_LOADING = 'APP_LOADING'
export const APP_LOADED_SUCCESS = 'APP_LOADED_SUCCESS'

// AUTH TYPES

export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

// POSTS TYPES

export const POSTS_GET_REQUEST = 'POSTS_GET_REQUEST'
export const POSTS_GET_SUCCESS = 'POSTS_GET_SUCCESS'
export const POSTS_GET_FAILURE = 'POSTS_GET_FAILURE'
